// Round-two visual furnishing checks: new shapes must stay aligned with the unchanged
// semantic envelopes that colliders, interaction points and camera poses are built from.
import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from 'three';
import {buildRoomModel} from '../dist/scene_model.js';import {buildInteractiveScene} from '../dist/interactive_scene.js';
import {styledGeometry,decorPieces,styleContext,setStyleContext} from '../dist/furnishing.js';import {createCollisionWorld} from '../dist/roam_physics.js';
const spec=JSON.parse(fs.readFileSync('dist/scene.json')),doc=JSON.parse(fs.readFileSync('dist/parameters.json')),configs=JSON.parse(fs.readFileSync('dist/interaction_config.json')),checks=[];
function check(name,fn){fn();checks.push(name);}
const plane=new THREE.Plane(new THREE.Vector3(0,-1,0),1.15),model=buildRoomModel(doc,spec,plane);setStyleContext(styleContext(spec.nodes));
const nodes=new Map(spec.nodes.map(n=>[n.name,n]));
function envelope(n){const [x,z,y]=n.position,[w,d,h]=n.size,round=n.shape!=='box';return new THREE.Box3(new THREE.Vector3(x-(round?w:w/2),y-(n.shape==='sphere'?h:h/2),z-(round?d:d/2)),new THREE.Vector3(x+(round?w:w/2),y+(n.shape==='sphere'?h:h/2),z+(round?d:d/2)));}
function overshoot(box,env){return Math.max(env.min.x-box.min.x,box.max.x-env.max.x,env.min.y-box.min.y,box.max.y-env.max.y,env.min.z-box.min.z,box.max.z-env.max.z);}
// Intentional, bounded exceptions: draped cloth, the task-lamp arm, globe lamp, mug handle.
const allowance=[[/^Bedding$/,.40],[/^Cream_throw$/,.30],[/^Desk_lamp_/,.20],[/^Floor_lamp_shade$/,.10],[/^Coffee_cup$/,.03],[/_plant_leaf\d$/,.40],[/^Toilet_bowl$/,.11],[/^Extractor_pipe$/,.08]];
check('scene.json semantic parts are unchanged in count, names, positions and sizes',()=>{assert.equal(spec.nodes.length,244);const names=model.children.flatMap(m=>m.userData.parts);assert.equal(new Set(names).size,244);assert.deepEqual([...names].sort(),spec.nodes.map(n=>n.name).sort());});
check('styled furniture stays inside its semantic envelope (colliders and poses remain valid)',()=>{const report=[];for(const n of spec.nodes){if(!['furniture','soft'].includes(n.layer)||n.rotation.some(r=>Math.abs(r)>.01))continue;const g=styledGeometry(n);if(!g)continue;g.computeBoundingBox();const over=overshoot(g.boundingBox,envelope(n)),limit=allowance.find(([re])=>re.test(n.name))?.[1]??.015;if(over>limit)report.push(n.name+' '+over.toFixed(3));}assert.deepEqual(report,[]);});
check('collision proxies enclose the visible furniture they stand for',()=>{const world=createCollisionWorld(spec,configs),slack={chair:.09};let count=0;
 // Chair: the proxy is the seat footprint; feet may pass over the low star base.
 for(const c of configs.filter(c=>c.collisionProxy)){const boxes=world.boxes.filter(b=>b.name.startsWith(c.id+'_proxy'));assert(boxes.length,'proxy '+c.id);const vis=new THREE.Box3();for(const n of spec.nodes.filter(n=>n.layer==='furniture'&&c.object.includes(n.name))){const g=styledGeometry(n);if(!g)continue;g.computeBoundingBox();if(g.boundingBox.min.y<1.75)vis.union(g.boundingBox);}if(vis.isEmpty())continue;count++;
  const u={minX:Math.min(...boxes.map(b=>b.minX)),maxX:Math.max(...boxes.map(b=>b.maxX)),minZ:Math.min(...boxes.map(b=>b.minZ)),maxZ:Math.max(...boxes.map(b=>b.maxZ))},out=Math.max(u.minX-vis.min.x,vis.max.x-u.maxX,u.minZ-vis.min.z,vis.max.z-u.maxZ);assert(out<(slack[c.id]??.03),c.id+' visual exceeds proxy by '+out.toFixed(3));}assert(count>=9);});
check('moving parts keep their envelope so door/drawer collision and animation pivots match',()=>{const adapter=buildInteractiveScene(doc,spec,plane,configs);for(const c of configs)for(const a of c.animation)for(const name of a.parts){const n=nodes.get(name);if(!n||n.rotation.some(r=>Math.abs(r)>.01))continue;const mesh=adapter.parts.get(name);assert(mesh,'part '+name);mesh.geometry.computeBoundingBox();const over=overshoot(mesh.geometry.boundingBox,envelope(n)),limit=allowance.find(([re])=>re.test(name))?.[1]??.015;assert(over<=limit,name+' moving part exceeds envelope by '+over.toFixed(3));}
 let draws=0;adapter.root.traverse(m=>{if(m.isMesh)draws++;});assert(draws<100,'roam draws '+draws);adapter.dispose();});
const decor=decorPieces(spec).map(d=>{d.geometry.computeBoundingBox();return d;});
check('seated, lying and sleeping camera poses do not clip into new cushions or decor',()=>{const flat=/shadow|Skirting|fringe|Ceiling_lights|Balcony/i;for(const c of configs)for(const [key,p]of Object.entries(c.cameraPose)){for(const q of [p.position,...p.waypoints]){const eye=new THREE.Vector3(...q);for(const d of decor){if(flat.test(d.name))continue;const dist=d.geometry.boundingBox.distanceToPoint(eye);assert(dist>.045,c.id+'.'+key+' eye within '+dist.toFixed(3)+' of '+d.name);}}}});
check('floor-standing decor is inside existing colliders or outside the walkable house',()=>{const world=createCollisionWorld(spec);for(const d of decor){const b=d.geometry.boundingBox;if(b.min.y>.30||/shadow|Skirting|fringe/i.test(d.name))continue;const cx=(b.min.x+b.max.x)/2,cz=(b.min.z+b.max.z)/2,outside=cz<0||cx<0||cx>spec.derived.width||cz>spec.derived.total_depth;
 const covered=world.boxes.some(w=>b.min.x>=w.minX-.03&&b.max.x<=w.maxX+.03&&b.min.z>=w.minZ-.03&&b.max.z<=w.maxZ+.03);assert(outside||covered,d.name+' would be walk-through');}});
check('materials are physically based with separated fabric, wood, tile, metal and glass response',()=>{const by=new Map();model.traverse(m=>{if(m.isMesh&&m.material.userData.styleKey)by.set(m.material.userData.styleKey,m.material);});for(const k of ['wood','tile','metal','glass','linen','oat','knit','curtain','rug'])assert(by.has(k),'material '+k);
 assert(by.get('metal').metalness>.8&&by.get('metal').roughness<.35);assert(by.get('glass').transparent&&by.get('glass').opacity<.3);assert(by.get('oat').roughness>.9&&by.get('tile').roughness<.4);assert(by.get('wood').map&&by.get('linen').map&&by.get('tile').map);
 assert(model.children.length<60);let tris=0;model.traverse(m=>{if(m.isMesh)tris+=m.geometry.index.count/3;});assert(tris<160000,'triangles '+tris);});
const tris=model.children.reduce((a,m)=>a+m.geometry.index.count/3,0);
const result={version:'1.3.0',passed:true,checks,drawBatches:model.children.length,triangles:tris,decorPieces:decor.length,verification:'Node with real Three.js geometry, the actual InteractionSystem configuration and collision builder; no browser or physical iPhone execution'};
fs.writeFileSync('dist/furnishing_checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
