// Round three checks: first-person hands, movement during interaction, toilet lid/seat,
// hob burners and range hood, drawer structure, and recalibrated collision passages.
// Executes the real configuration, adapter, InteractionSystem and HandRig in Node.
import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from 'three';
import {buildInteractiveScene} from '../dist/interactive_scene.js';import {InteractionSystem,EYE_HEIGHT,findFloorRoute} from '../dist/interaction_system.js';
import {Walker,isWalkable,moveWithCollision,createCollisionWorld,PLAYER_RADIUS} from '../dist/roam_physics.js';import {HandRig} from '../dist/first_person_hands.js';
const spec=JSON.parse(fs.readFileSync('dist/scene.json')),doc=JSON.parse(fs.readFileSync('dist/parameters.json')),configs=JSON.parse(fs.readFileSync('dist/interaction_config.json')),checks=[],report={};
function check(name,fn){fn();checks.push(name);}
const adapter=buildInteractiveScene(doc,spec,new THREE.Plane(new THREE.Vector3(0,-1,0),4),configs),world=adapter.world,camera=new THREE.PerspectiveCamera(70,.46,.035,200);
const walker=new Walker(world,{x:1.2,z:5.94}),hands=new HandRig({adapter,camera}),system=new InteractionSystem({configs,adapter,camera,walker,onWake(){},hands});adapter.root.visible=true;system.start();let time=0;
const tick=(n=1,input=null)=>{for(let i=0;i<n;i++){time+=1/60;if(input&&!system.locked)walker.update(1/60,input,system.look.yaw);system.update(1/60,time,!!input);}};
function aim(id,approach){const c=system.registry.get(id),p=c.interactionPoints[0],a=approach||p.approach;hands.reset();walker.position={x:a[0],z:a[1]};walker.velocity={x:0,z:0};system.crouch=0;camera.position.set(a[0],EYE_HEIGHT,a[1]);const d=new THREE.Vector3(...p.position).sub(camera.position);system.look={yaw:Math.atan2(-d.x,-d.z),pitch:Math.atan2(d.y,Math.hypot(d.x,d.z))};system.lookTarget={...system.look};system.orient();tick(3);system.select();assert.equal(system.focus?.config.id,id,'focus '+id);return c;}
const settle=(n=400)=>{for(let i=0;i<n&&(system.animations.size||hands.gesture);i++)tick();};
// Points of the hand that must never be inside furniture/walls other than the handled part.
function intrusions(g){const h=hands.hands[g?.side||'right'],ign=new Set(g?[g.config.id,g.key+'_motion',...g.config.object,...g.config.animation.flatMap(a=>a.parts)]:[]),pts=[h.T,h.T.clone().addScaledVector(h.D,.06),h.W].filter(Boolean),bad=[];
 for(const b of [...world.cameraBoxes,...world.glazingBoxes,...world.dynamicBoxes]){if(ign.has(b.name)||(g&&(b.name.startsWith(g.config.id+'_')||b.name.startsWith(g.config.id+'#'))))continue;for(const p of pts)if(p.x>b.minX+.004&&p.x<b.maxX-.004&&p.y>b.minY+.004&&p.y<b.maxY-.004&&p.z>b.minZ+.004&&p.z<b.maxZ-.004)bad.push(b.name);}return bad;}

const handObjects=configs.filter(c=>c.handPose&&c.actions.some(a=>a.kind==='toggle'||a.kind==='set')).map(c=>c.id);
check('every operable object declares hand pose, hand target, movable parts and state in its configuration',()=>{for(const c of configs){for(const k of ['object','interactionPoints','actions','handPose','handTarget','movableParts','animation','collisionProxy','state'])assert(k in c,c.id+' lacks '+k);
  if(c.actions.some(a=>a.kind==='toggle'||a.kind==='set'))assert(c.handPose&&c.handTarget,c.id+' has no hand gesture');for(const m of c.movableParts)assert(m.part&&m.type&&(m.pivot||m.range),c.id+' movable part without pivot/range');}
 assert(handObjects.length>=30);});
check('hand reaches and grips before the part moves, follows it, then releases and retracts',()=>{const rows=[];
 for(const id of handObjects){const c=aim(id),action=system.available(c).find(a=>a.kind==='toggle'||a.kind==='set');assert(system.execute(action.id,id),id);const g=hands.gesture;assert(g,'gesture '+id);const key=g.key,start=system.progress.get(key);let contactErr=null,maxDrive=0,movedBeforeContact=false,phases=new Set(),bad=[];
  for(let i=0;i<420&&(hands.gesture||system.animations.has(key));i++){tick();const cur=hands.gesture;if(!cur)continue;phases.add(cur.phase);if(cur.phase==='reach'&&Math.abs(system.progress.get(key)-start)>1e-6)movedBeforeContact=true;
   const t=adapter.handTarget(key),h=hands.hands[cur.side];if(cur.phase==='contact'&&contactErr===null&&cur.mode==='grip')contactErr=h.T.distanceTo(t.position);if(cur.phase==='drive')maxDrive=Math.max(maxDrive,h.T.distanceTo(t.position));bad.push(...intrusions(cur));}
  settle();assert(!movedBeforeContact,id+' moved before the hand arrived');assert(phases.has('reach')&&phases.has('retract'),id+' phases '+[...phases]);
  if(g.mode==='grip'){assert(contactErr!==null&&contactErr<.025,id+' grip error '+contactErr);assert(maxDrive<.035,id+' hand lost the handle '+maxDrive);assert(phases.has('drive'));}
  assert.equal(new Set(bad).size,0,id+' hand inside '+[...new Set(bad)]);assert(!hands.gesture);rows.push([id,g.mode,contactErr===null?null:+contactErr.toFixed(4),+maxDrive.toFixed(4)]);
  // put it back for the next object
  const back=system.available(c).find(a=>a.kind==='toggle'||(a.kind==='set'&&a.value===0));if(back){aim(id);system.execute(back.id,id);settle();}}
 report.gestures=rows;});
check('hand gesture type follows the object: pull, swing, slide, press, turn, lift',()=>{const want={Desk_drawer_front:['pull','grip'],wardrobe:['swing','grip'],entry_door:['swing','grip'],bath_door:['slide','grip'],Desk_lamp:['press','point'],hob_front:['turn','pinch'],toilet:['lift','hook'],aircon:['remote','point']};for(const [id,[gesture,grip]]of Object.entries(want)){const hp=system.registry.get(id).handPose;assert.equal(hp.gesture,gesture,id);assert.equal(hp.grip,grip,id);}});
check('player keeps walking and turning while a drawer or door is opening',()=>{const c=aim('Desk_drawer_front_03');assert(system.execute('toggle',c.id));tick(5);assert(!system.locked);const yaw=system.look.yaw;system.turn(60,0);tick(2);assert.notEqual(system.lookTarget.yaw,yaw);
 for(let i=0;i<60&&!['drive'].includes(hands.gesture?.phase);i++)tick();const before={...walker.position};tick(30,{x:0,y:1});assert(Math.hypot(walker.position.x-before.x,walker.position.z-before.z)>.08,'walker did not move during the gesture');settle();assert(isWalkable(world,walker.position.x,walker.position.z));aim(c.id);system.execute('toggle',c.id);settle();});
check('fixed postures still hold the player; standing up releases them',()=>{const c=aim('chair');assert(system.execute('sit','chair'));assert(system.locked);for(let i=0;i<200&&system.motion;i++)tick();assert(system.occupied);const h=hands.hands.right;tick(40);assert(h.lower>.95,'hands lowered while seated');assert(system.release());for(let i=0;i<300&&(system.motion||system.occupied);i++)tick();assert(!system.locked);});
check('toilet lid and seat are separate hinged parts with valid order of operation',()=>{const c=aim('toilet'),names=()=>system.available(c).map(a=>a.id);assert(names().includes('lid')&&!names().includes('seat'),'seat must wait for the lid');assert(system.execute('lid','toilet'));settle();
 const lid=adapter.bindings.get('toilet')[0].group,seatKey='toilet#seat';assert(Math.abs(lid.rotation.x-1.62)<.01,'lid open');assert.equal(adapter.bindings.get(seatKey)[0].group.rotation.x,0);aim('toilet');assert(names().includes('seat'));assert(system.execute('seat','toilet'));settle();
 assert(Math.abs(adapter.bindings.get(seatKey)[0].group.rotation.x-1.50)<.01);aim('toilet');assert(!names().includes('lid'),'lid cannot close over a raised seat');assert(system.execute('seat','toilet'));settle();aim('toilet');assert(system.execute('lid','toilet'));settle();assert(Math.abs(lid.rotation.x)<.01);
 const hinge=new THREE.Vector3(...c.animation[0].pivot);assert(Math.abs(hinge.z-(spec.nodes.find(n=>n.name==='Toilet_bowl').position[1]+.16))<.001);});
check('each hob burner has its own knob, ignites, steps low/medium/high and goes out',()=>{const levels={};for(const id of ['hob_front','hob_back']){let c=aim(id);const [rot,flame]=adapter.bindings.get(id);const other=id==='hob_front'?'hob_back':'hob_front';
  assert.deepEqual(system.available(c).map(a=>a.id),['ignite']);assert(system.execute('ignite',id));settle();assert(flame.flame.visible);assert(Math.abs(rot.group.rotation.y+4*.55)<.01,'knob angle follows level');assert.equal(system.progress.get(other),0,'other burner untouched');
  const h={};for(const level of ['low','high','medium']){c=aim(id);assert(system.execute(level,id));settle();adapter.animateEffects(1000);h[level]=flame.flame.scale.y;}assert(h.low<h.medium&&h.medium<h.high,'flame grows with the knob');
  c=aim(id);assert.deepEqual(system.available(c).map(a=>a.id).slice(0,1),['off']);assert(system.execute('off',id));settle();assert(!flame.flame.visible);assert(Math.abs(rot.group.rotation.y)<.01);levels[id]=h;}
 report.flameScale=levels;});
check('range hood switches on with light and indicator, and off again',()=>{const c=aim('range_hood');assert(system.execute('toggle','range_hood'));settle();const [light,led]=adapter.bindings.get('range_hood');assert(light.light.intensity>.5);assert(led.meshes[0].material.emissiveIntensity>1);aim('range_hood');assert(system.execute('toggle','range_hood'));settle();assert.equal(light.light.intensity,0);});
check('drawers are complete boxes (bottom, sides, back) that slide out with their fronts',()=>{for(const id of ['Desk_drawer_front_02','Nightstand_interactive_front1']){const g=adapter.bindings.get(id)[0].group,box0=new THREE.Box3().setFromObject(g);assert(box0.getSize(new THREE.Vector3()).x>.30,'drawer depth');let tris=0;g.traverse(m=>{if(m.isMesh)tris+=m.geometry.index.count/3;});assert(tris>=60,'box panels');
  aim(id);system.execute('toggle',id);settle();const box1=new THREE.Box3().setFromObject(g),off=configs.find(c=>c.id===id).animation[0].offset[0];assert(Math.abs((box1.min.x-box0.min.x)-off)<.002);aim(id);system.execute('toggle',id);settle();}});
check('hands stay out of walls when the player faces a wall closely',()=>{hands.reset();walker.position={x:2.0,z:PLAYER_RADIUS+.001};system.look={yaw:0,pitch:-.3};system.lookTarget={...system.look};tick(30);assert.equal(intrusions(null).length,0);for(const side of ['right','left']){const h=hands.hands[side];assert(h.T.z>-.001,'hand inside balcony wall');}});
check('idle hands are visible at the bottom of the portrait view and stay still when idle',()=>{hands.reset();walker.position={x:1.2,z:6.2};walker.velocity={x:0,z:0};walker.speed=0;system.look={yaw:0,pitch:0};system.lookTarget={...system.look};tick(60);camera.updateMatrixWorld();for(const side of ['right','left']){const p=hands.hands[side].T.clone().project(camera);assert(Math.abs(p.x)<1&&p.y<-.4&&p.y>-1.3,side+' idle hand off screen '+p.toArray());}
 let active=false;for(let i=0;i<10;i++){time+=1/60;active=system.update(1/60,time)||active;}assert(!active,'idle hands keep the renderer busy');});
check('collision proxies: player radius 0.16 m, 50-60 cm passages pass, narrow real gaps are reachable',()=>{assert.equal(PLAYER_RADIUS,.16);
 const synthetic=gap=>{const w={width:4,depth:4,boxes:[{minX:0,maxX:1,minZ:1,maxZ:2},{minX:1+gap,maxX:4,minZ:1,maxZ:2}]};return moveWithCollision(w,{x:1+gap/2+.03,z:.5},0,2).z>2.2;};assert(synthetic(.50)&&synthetic(.60)&&synthetic(.34)&&!synthetic(.30));
 const walk=(from,dx,dz,test)=>{const p=moveWithCollision(world,from,dx,dz);assert(test(p),JSON.stringify([from,p]));return p;};
 walk({x:2.1,z:5.99},1.5,0,p=>p.x>3.45);                        // between sofa front and coffee table (36 cm)
 walk({x:3.2,z:4.60},.7,0,p=>p.x>3.8);                          // between nightstand and bedroom partition (36 cm)
 walk({x:1.56,z:1.55},0,1.5,p=>p.z>2.95);                       // between desk chair and bed foot (60 cm)
 walk({x:3.30,z:6.90},.5,0,p=>p.x>3.39&&p.x<3.41);               // stopped by the floor lamp, not walking through it
 assert(findFloorRoute(world,{x:1.8,z:7.95},{x:3.15,z:8.58}),'into the bathroom to the toilet');assert(findFloorRoute(world,{x:1.2,z:6.9},{x:1.6,z:8.9}),'into the kitchen');
 assert(findFloorRoute(world,{x:2.0,z:6.0},{x:3.2,z:4.5}),'living room to the bed side');assert(!isWalkable(world,3.7,6.84),'floor lamp has a collider');assert(!isWalkable(world,3.76,7.19),'cart has a collider');
 const legacy=createCollisionWorld(spec);report.passages={sofaTableLegacyR19:isWalkable(legacy,2.6,6.0,.19),sofaTableNow:isWalkable(world,2.6,6.0)};});
const result={version:'1.4.0',passed:true,checks,...report,verification:'Node with real Three.js geometry, the runtime configuration, InteractionSystem, HandRig IK and collision; no browser or physical iPhone execution'};
fs.writeFileSync('dist/hands_checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify({version:result.version,passed:true,checks:checks.length}));
