import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from 'three';
import {createInteractionConfig} from '../dist/interaction_config.js';import {buildInteractiveScene} from '../dist/interactive_scene.js';import {InteractionSystem,findFloorRoute,EYE_HEIGHT} from '../dist/interaction_system.js';import {Walker,isWalkable,moveWithCollision} from '../dist/roam_physics.js';import {RoamController} from '../dist/roam.js';
const spec=JSON.parse(fs.readFileSync('dist/scene.json')),doc=JSON.parse(fs.readFileSync('dist/parameters.json')),configs=JSON.parse(fs.readFileSync('dist/interaction_config.json')),checks=[];
function check(name,fn){fn();checks.push(name);}
const wallClip=new THREE.Plane(new THREE.Vector3(0,-1,0),4),adapter=buildInteractiveScene(doc,spec,wallClip,configs),world=adapter.world,camera=new THREE.PerspectiveCamera(70,.48,.035,200),walker=new Walker(world,{x:1.2,z:5.9375}),system=new InteractionSystem({configs,adapter,camera,walker,onWake(){}});adapter.root.visible=true;system.start();let time=0;
function tick(n=120,move=false){for(let i=0;i<n;i++){time+=1/60;system.update(1/60,time,move);}}
function aim(config,approach=config.interactionPoints[0].approach){assert(isWalkable(world,...approach),'approach '+config.id+' not walkable');walker.position={x:approach[0],z:approach[1]};camera.position.set(approach[0],EYE_HEIGHT,approach[1]);const delta=new THREE.Vector3(...config.interactionPoints[0].position).sub(camera.position);system.look={yaw:Math.atan2(-delta.x,-delta.z),pitch:Math.atan2(delta.y,Math.hypot(delta.x,delta.z))};system.lookTarget={...system.look};system.orient();system.select();assert.equal(system.focus?.config.id,config.id,'focus mismatch '+config.id+' vs '+system.focus?.config.id);}
function clearEye(position){const margin=.018;for(const n of spec.nodes){if(!n.wall&&n.layer!=='furniture'&&n.layer!=='soft')continue;if(n.name==='Bed_rug'||n.name==='Living_rug')continue;const [x,z,y]=n.position,[w,d,h]=n.size;let g; // Bounding volumes from actual original geometry, not the coarse whole-furniture box.
 const obj=adapter.parts.get(n.name);if(obj){obj.updateWorldMatrix(true,false);g=new THREE.Box3().setFromObject(obj);}else{const sphere=n.shape==='sphere',cylinder=n.shape==='cylinder';g=new THREE.Box3(new THREE.Vector3(x-(sphere||cylinder?w:w/2),y-(sphere?h:h/2),z-(sphere||cylinder?d:d/2)),new THREE.Vector3(x+(sphere||cylinder?w:w/2),y+(sphere?h:h/2),z+(sphere||cylinder?d:d/2)));}
 if(position.x>g.min.x-margin&&position.x<g.max.x+margin&&position.y>g.min.y-margin&&position.y<g.max.y+margin&&position.z>g.min.z-margin&&position.z<g.max.z+margin)assert.fail('Eye intersects '+n.name+' at '+position.toArray());}}
check('configuration schema and all first-batch furniture categories',()=>{assert.equal(new Set(configs.map(c=>c.id)).size,configs.length);for(const c of configs)for(const key of ['object','interactionPoints','actions','cameraPose','animation','state'])assert(key in c);for(const id of ['chair','desk','sofa','bed','toilet','wardrobe','bath_door','entry_door','curtains','Desk_lamp','Bed_lamp','Floor_lamp'])assert(system.registry.has(id));assert.equal(configs.filter(c=>c.id.startsWith('Desk_drawer_front')).length,6);});
check('existing geometry adapted only at runtime with bounded draw calls',()=>{let draws=0;adapter.root.traverse(m=>{if(m.isMesh)draws++;});assert(draws<100);assert(adapter.parts.has('Kitchen_cabinet_interactive_front0'));assert(adapter.parts.has('Vanity_interactive_front0'));assert(adapter.parts.has('Nightstand_interactive_front0'));assert.equal(spec.nodes.length,244);});
check('living room to bedroom collision route and bed clearance',()=>{assert(findFloorRoute(world,walker.position,{x:1.52,z:2.125}));assert(findFloorRoute(world,walker.position,{x:2.885,z:4.24275}));const p=moveWithCollision(world,{x:1.4,z:3.2},2,0);assert(p.x<1.7);});
for(const id of ['chair','desk','sofa','bed','toilet'])check('all '+id+' poses animate to real scale with clear camera and safe stand-up',()=>{const c=system.registry.get(id);for(const action of c.actions.filter(a=>a.kind==='pose')){aim(c);const standing=camera.position.clone(),floor={...walker.position};assert(system.execute(action.id,c.id));assert(system.locked);time+=1/60;system.update(1/60,time);assert(camera.position.distanceTo(new THREE.Vector3(...c.cameraPose[action.cameraPose].position))>.01,'camera instantly teleported');for(let i=0;i<300&&system.motion;i++){time+=1/60;system.update(1/60,time);clearEye(camera.position);}assert(!system.motion);assert(camera.position.distanceTo(new THREE.Vector3(...c.cameraPose[action.cameraPose].position))<.001);const position=camera.position.clone();system.turn(80,-25);system.update(1/60,time);assert(camera.position.distanceTo(position)<.00001);assert.equal(walker.position.x,floor.x);assert.equal(walker.position.z,floor.z);assert(system.release());for(let i=0;i<300&&system.motion;i++){time+=1/60;system.update(1/60,time);clearEye(camera.position);}assert(!system.occupied&&!system.locked);assert(isWalkable(world,walker.position.x,walker.position.z));assert(camera.position.distanceTo(standing)<.001);}});
check('bed sleep closes eyes and joystick movement wakes and restores walking',()=>{const c=system.registry.get('bed');aim(c);assert(system.execute('sleep','bed'));tick(180);assert(system.sleepAmount>.98);system.update(1/60,time,true);assert(system.motion?.exiting);tick(200);assert(!system.occupied);assert(system.sleepAmount<.005);});
check('sitting to lying to sitting uses shared pose system',()=>{const c=system.registry.get('sofa');aim(c);assert(system.execute('sit','sofa'));tick();assert(system.execute('lie','sofa'));tick();assert.equal(system.occupied.action.id,'lie');assert(system.execute('sit','sofa'));tick();assert.equal(system.occupied.action.id,'sit');system.release();tick();});
check('drawer and cupboard doors animate, preserve state, and affect collision',()=>{for(const c of configs.filter(c=>c.actions[0]?.kind==='toggle'&&c.animation.some(a=>a.collision)&&!['entry_door','bath_door'].includes(c.id))){aim(c);const initial=system.progress.get(c.id);assert(system.execute('toggle',c.id));system.update(.05,time);assert(system.progress.get(c.id)>initial&&system.progress.get(c.id)<1);assert(!system.locked,'opening '+c.id+' must not freeze the player');tick();assert.equal(system.progress.get(c.id),1,c.id);assert.equal(system.states.get(c.id).open,true);assert(system.execute('toggle',c.id));tick();assert.equal(system.progress.get(c.id),0,c.id);}});
check('bathroom sliding door closes passage and reopens it',()=>{const c=system.registry.get('bath_door');aim(c);assert(system.execute('toggle',c.id));tick();assert.equal(system.progress.get(c.id),0);assert(!findFloorRoute(world,{x:1.8,z:7.95},{x:2.8,z:7.95}));aim(c);assert(system.execute('toggle',c.id));tick();assert(findFloorRoute(world,{x:1.8,z:7.95},{x:2.8,z:7.95}));});
check('door closing on a player is blocked without trapping them',()=>{const c=system.registry.get('bath_door');aim(c,[2.3,7.90]);assert(system.execute('toggle',c.id));tick(220);assert.equal(system.states.get(c.id).open,true);assert(isWalkable(world,walker.position.x,walker.position.z));assert(!system.animations.size);});
check('entry door hinge moves smoothly while house boundary stays closed',()=>{const c=system.registry.get('entry_door');aim(c);assert(system.execute('toggle',c.id));system.update(.05,time);const p=system.progress.get(c.id);assert(p>0&&p<1);tick();assert.equal(system.progress.get(c.id),0);assert(!isWalkable(world,-.2,8.85));aim(c);assert(system.execute('toggle',c.id));tick();assert.equal(system.progress.get(c.id),1);});
check('curtains and sheer interpolate coverage instead of toggling visibility',()=>{for(const id of ['curtains','sheer']){const c=system.registry.get(id);aim(c);assert(system.execute('toggle',id));system.update(.1,time);const b=adapter.bindings.get(id)[0];assert(b.group.scale.x>1&&b.group.scale.x<3.5);tick();assert(b.group.scale.x>2);aim(c);assert(system.execute('toggle',id));tick();assert.equal(b.group.scale.x,1);}});
check('lamps illuminate room, laptop has a real screen, other equipment has visible effects',()=>{for(const id of ['Desk_lamp','Bed_lamp','Floor_lamp','laptop','aircon','hob_front','hob_back','range_hood','shower']){const c=system.registry.get(id),on=id.startsWith('hob_')?'ignite':'toggle',off=id.startsWith('hob_')?'off':'toggle';let a=c.interactionPoints[0].approach;aim(c,a);assert(system.execute(on,id));tick();const list=adapter.bindings.get(id),b=list.find(x=>!x.group);if(b.light)assert(b.light.intensity>.5);else if(b.water)assert(b.water.visible);else if(b.flame)assert(b.flame.visible);else assert(b.meshes[0].material.emissiveIntensity>.2);if(id==='laptop')assert(b.meshes[0].material.map);aim(c,a);assert(system.execute(off,id));tick();assert.equal(system.progress.get(id),0);if(b.flame)assert(!b.flame.visible);}});
check('window panes slide inside existing frames and cannot leave the house',()=>{for(const id of ['living_window','bath_window','balcony_window']){const c=system.registry.get(id);aim(c);const b=adapter.bindings.get(id)[0],start=b.group.position.clone();assert(system.execute('toggle',id));system.update(.1,time);assert(b.group.position.distanceTo(start)>.001);tick();assert.equal(system.progress.get(id),1);aim(c);assert(system.execute('toggle',id));tick();assert(b.group.position.distanceTo(start)<.0001);}});
check('focus cannot interact through walls or via remote explicit IDs',()=>{walker.position={x:1.2,z:6.7};camera.position.set(1.2,EYE_HEIGHT,6.7);system.look={yaw:0,pitch:0};system.lookTarget={...system.look};system.orient();system.select();assert(!system.execute('sit','bed'));assert(!system.execute('toggle','wardrobe'));});
class Target{constructor(){this.events=new Map();this.hidden=true;this.style={};this.captured=new Set();this.defaultView=this;this.children=[];}addEventListener(n,f){if(!this.events.has(n))this.events.set(n,[]);this.events.get(n).push(f);}removeEventListener(n,f){this.events.set(n,(this.events.get(n)||[]).filter(x=>x!==f));}fire(n,{id=1,x=0,y=0,key='',...rest}={}){let prevented=false;for(const f of [...(this.events.get(n)||[])])f({pointerId:id,clientX:x,clientY:y,key,cancelable:true,preventDefault(){prevented=true;},stopPropagation(){},...rest});return prevented;}setPointerCapture(id){this.captured.add(id);}hasPointerCapture(id){return this.captured.has(id);}releasePointerCapture(id){this.captured.delete(id);}getBoundingClientRect(){return {left:24,top:550,width:120,height:120};}count(){return [...this.events.values()].reduce((a,b)=>a+b.length,0);}querySelector(id){return this.elements[id];}createElement(){return new Target();}replaceChildren(){this.children=[];}append(b){this.children.push(b);}}
const fakeDoc=new Target(),hud=new Target();hud.elements=Object.fromEntries(['interaction-prompt','interaction-button','interaction-more','interaction-choices','interaction-caption','sleep-overlay','interaction-notice'].map(id=>['#'+id,new Target()]));const joystick=new Target(),knob=new Target(),lookZone=new Target(),scene=new THREE.Scene(),original=new THREE.Group();original.visible=true;scene.add(original);const r=new RoamController({scene,camera:new THREE.PerspectiveCamera(70,.48,.035,200),spec,modelDoc:doc,wallClip,originalModel:original,hud,joystick,knob,lookZone,onWake(){},document:fakeDoc});
check('first-person joystick plus simultaneous right look stays independent',()=>{r.enter();assert(!original.visible);assert(r.adapter.root.visible);assert.equal(r.camera.position.y,EYE_HEIGHT);joystick.fire('pointerdown',{id:1,x:84,y:574});lookZone.fire('pointerdown',{id:2,x:300,y:350});const start={...r.walker.position};for(let i=1;i<35;i++){lookZone.fire('pointermove',{id:2,x:300+i,y:350});r.update(i*16.67);}assert(r.walker.position.z<start.z);assert(r.yaw<0);assert.equal(r.joystickId,1);assert.equal(r.lookId,2);joystick.fire('pointerup',{id:1});assert.equal(r.lookId,2);lookZone.fire('pointerup',{id:2});});
check('context action button sits, joystick stands up, and idle rendering stops',()=>{r.resetInput();const c=r.configs.find(c=>c.id==='chair'),a=c.interactionPoints[0].approach;r.walker.position={x:a[0],z:a[1]};r.camera.position.set(a[0],EYE_HEIGHT,a[1]);const d=new THREE.Vector3(...c.interactionPoints[0].position).sub(r.camera.position);r.interactions.look={yaw:Math.atan2(-d.x,-d.z),pitch:Math.atan2(d.y,Math.hypot(d.x,d.z))};r.interactions.lookTarget={...r.interactions.look};let t=1000;for(let i=0;i<30;i++)r.update(t+=16.67);assert.equal(r.interactions.focus.config.id,'chair');assert.equal(r.button.textContent,'坐下');r.button.fire('click');for(let i=0;i<150;i++)r.update(t+=16.67);assert.equal(r.interactions.occupied.action.id,'sit');assert.equal(r.button.textContent,'起身');joystick.fire('pointerdown',{id:6,x:84,y:574});r.update(t+=16.67);assert(r.interactions.motion.exiting);joystick.fire('pointerup',{id:6});let active;for(let i=0;i<250;i++)active=r.update(t+=16.67);assert(!r.interactions.occupied);assert.equal(active,false);});
check('cancel/background stop inputs; 20 entries do not duplicate UI or listeners',()=>{r.resetInput();joystick.fire('pointerdown',{id:3,x:84,y:575});fakeDoc.fire('visibilitychange');assert.equal(r.input.y,0);assert.equal(r.joystickId,null);r.exit();assert(original.visible&&!r.adapter.root.visible);const initial=scene.children.length;let count;for(let i=0;i<20;i++){r.enter();const n=r.listeners.length;count??=n;assert.equal(n,count);r.enter();assert.equal(r.listeners.length,count);r.exit();assert.equal(joystick.count()+lookZone.count()+fakeDoc.count()+r.button.count()+r.more.count(),0);assert.equal(scene.children.length,initial);assert.equal(hud.hidden,true);}});
check('hint dwell, aim hysteresis and reach cannot authorize distant or occluded use',()=>{const c=system.registry.get('chair');aim(c);system.focus=null;system.pendingFocus=null;system.focusDwell=system.focusLost=0;for(let i=0;i<6;i++)system.select(1/60);assert.equal(system.focus,null);for(let i=0;i<3;i++)system.select(1/60);assert.equal(system.focus.config.id,'chair');const yaw=system.look.yaw;for(let i=0;i<45;i++){system.look.yaw=yaw+Math.sin(i)*.07;system.orient();system.select(1/60);assert.equal(system.focus.config.id,'chair');}walker.position={x:1.2,z:6.7};camera.position.set(1.2,EYE_HEIGHT,6.7);assert(!system.execute('sit','chair'));for(let i=0;i<14;i++)system.select(1/60);assert.notEqual(system.focus?.config.id,'chair');system.lookTarget={...system.look};});
check('pose paths start/finish softly, lift before release, and reject obstructed paths',()=>{for(const id of ['chair','sofa','bed','toilet']){const c=system.registry.get(id);aim(c);const begin=camera.position.clone();assert(system.execute('sit',id)||id==='toilet'&&system.execute('use',id));system.update(1/60,time);assert(camera.position.distanceTo(begin)<.002);tick(240);assert(!system.motion);const seated=camera.position.clone();assert(system.release());system.update(1/60,time);assert(system.locked&&system.motion.exiting);assert(camera.position.y>seated.y);assert(camera.position.distanceTo(seated)<.002);tick(240);assert(!system.locked);}
 const c=system.registry.get('chair');aim(c);const saved=c.cameraPose.sit.position;c.cameraPose.sit.position=[0,1,2];assert(!system.execute('sit','chair'));assert(!system.occupied&&!system.motion);c.cameraPose.sit.position=saved;});
check('mid-flight door and drawer reversal retains position, momentum and final state under repeated taps',()=>{for(const id of ['bath_door','entry_door','Desk_drawer_front']){const c=system.registry.get(id);assert(c,'existing drawer');aim(c);const origin=system.progress.get(id);assert(system.execute('toggle',id));tick(12);const p=system.progress.get(id),vel=system.animations.get(id).velocity;assert(p>0&&p<1);assert(system.execute('toggle',id));assert.equal(system.progress.get(id),p);assert.equal(system.animations.get(id).velocity,vel);assert.equal(system.animations.get(id).target,origin);tick(16);assert(Math.abs(system.progress.get(id)-origin)<Math.abs(p-origin));
 for(let i=0;i<11;i++){assert(system.execute('toggle',id));tick(2);}const target=+system.states.get(id).open;tick(240);assert.equal(system.progress.get(id),target);assert(!system.animations.has(id));aim(c);if(target!==origin){assert(system.execute('toggle',id));tick(240);}assert.equal(system.progress.get(id),origin);}});
check('camera turn filters touch impulses, clamps seated/lying head motion, and remains in clear space',()=>{for(const [id,action]of [['chair','sit'],['sofa','lie'],['bed','lie'],['toilet','use']]){const c=system.registry.get(id);aim(c);assert(system.execute(action,id));tick(240);const pose=system.occupied.pose,yaw=system.look.yaw;system.turn(5000,-5000);assert.equal(system.look.yaw,yaw);system.update(1/60,time);assert(Math.abs(system.look.yaw-yaw)>0&&Math.abs(system.look.yaw-system.lookTarget.yaw)>.01);tick(100);assert(Math.abs(Math.atan2(Math.sin(system.look.yaw-pose.yaw),Math.cos(system.look.yaw-pose.yaw)))<=pose.yawLimit+.0001);assert(system.look.pitch<=pose.pitchLimits[1]+.0001);clearEye(camera.position);assert(system.release());tick(240);}});
check('standing motion accelerates/stops gently and head bob never exceeds three millimetres',()=>{const w=new Walker(world,{x:1.2,z:6.7});const small=w.update(1/60,{x:0,y:-1},0);assert(small>0&&small<.20);for(let i=0;i<35;i++)w.update(1/60,{x:0,y:-1},0);const before=Math.hypot(w.velocity.x,w.velocity.z);w.update(1/60,{x:0,y:0},0);assert(Math.hypot(w.velocity.x,w.velocity.z)>0&&Math.hypot(w.velocity.x,w.velocity.z)<before);for(let i=0;i<180;i++)w.update(1/60,{x:0,y:0},0);assert.equal(w.velocity.x,0);assert.equal(w.velocity.z,0);
 system.focus=null;system.look={yaw:0,pitch:0};system.lookTarget={...system.look};walker.position={x:1.2,z:6.7};walker.speed=1.1;for(let i=0;i<120;i++){walker.travel+=.01;system.update(1/60,time);assert(Math.abs(camera.position.y-EYE_HEIGHT)<=.003001);}walker.speed=0;tick(180);assert.equal(system.bobAmount,0);});
check('prompt fades and stays non-actionable while switching; interrupted animation resumes across roam exits',()=>{r.enter();const c=r.configs.find(c=>c.id==='chair'),a=c.interactionPoints[0].approach;r.walker.position={x:a[0],z:a[1]};r.camera.position.set(a[0],EYE_HEIGHT,a[1]);const d=new THREE.Vector3(...c.interactionPoints[0].position).sub(r.camera.position);r.interactions.look={yaw:Math.atan2(-d.x,-d.z),pitch:Math.atan2(d.y,Math.hypot(d.x,d.z))};r.interactions.lookTarget={...r.interactions.look};let t=20000;for(let i=0;i<10;i++)r.update(t+=16.67);assert(+r.prompt.style.opacity>0&&+r.prompt.style.opacity<1);assert(r.button.disabled);for(let i=0;i<20;i++)r.update(t+=16.67);assert.equal(+r.prompt.style.opacity,1);assert(!r.button.disabled);r.interactions.turn(700,0);for(let i=0;i<15;i++)r.update(t+=16.67);assert(+r.prompt.style.opacity>0&&+r.prompt.style.opacity<1);assert(r.button.disabled);for(let i=0;i<30;i++)r.update(t+=16.67);assert.equal(+r.prompt.style.opacity,0);
 const door=r.configs.find(c=>c.id==='bath_door'),p=door.interactionPoints[0].approach;r.walker.position={x:p[0],z:p[1]};r.camera.position.set(p[0],EYE_HEIGHT,p[1]);const delta=new THREE.Vector3(...door.interactionPoints[0].position).sub(r.camera.position);r.interactions.look={yaw:Math.atan2(-delta.x,-delta.z),pitch:Math.atan2(delta.y,Math.hypot(delta.x,delta.z))};r.interactions.lookTarget={...r.interactions.look};r.interactions.orient();r.interactions.select();assert(r.perform('toggle','bath_door'));for(let i=0;i<8;i++)r.update(t+=16.67);const halfway=r.interactions.progress.get('bath_door');assert(halfway>0&&halfway<1);r.exit();assert.equal(r.interactions.progress.get('bath_door'),halfway);r.enter();for(let i=0;i<180;i++)r.update(t+=16.67);assert.equal(r.interactions.progress.get('bath_door'),0);r.exit();});

check('actual contextual button stays enabled and reverses a moving door without a snap',()=>{r.enter();const c=r.configs.find(c=>c.id==='bath_door'),a=c.interactionPoints[0].approach;r.walker.position={x:a[0],z:a[1]};r.camera.position.set(a[0],EYE_HEIGHT,a[1]);const d=new THREE.Vector3(...c.interactionPoints[0].position).sub(r.camera.position);r.interactions.look={yaw:Math.atan2(-d.x,-d.z),pitch:Math.atan2(d.y,Math.hypot(d.x,d.z))};r.interactions.lookTarget={...r.interactions.look};let t=30000;for(let i=0;i<40;i++)r.update(t+=16.67);assert(!r.button.disabled);const origin=r.interactions.progress.get(c.id);r.button.fire('click');for(let i=0;i<10;i++)r.update(t+=16.67);const p=r.interactions.progress.get(c.id);assert(p>0&&p<1);assert(!r.button.disabled);r.button.fire('click');assert.equal(r.interactions.progress.get(c.id),p);for(let i=0;i<200;i++)r.update(t+=16.67);assert.equal(r.interactions.progress.get(c.id),origin);r.exit();});
r.dispose();assert.equal(scene.children.length,1);
const result={version:'1.3.0',passed:true,checks,interactionObjects:configs.length,verification:'Executed real project configuration, Three.js runtime geometry, InteractionSystem, collision routes, camera paths and simulated Pointer Events in Node; no browser or physical iPhone execution'};fs.writeFileSync('dist/life_checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));adapter.dispose();
