// Execute the actual Viewer with a small DOM/renderer double. This is not browser QA.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const extra=(process.env.ROOM_BUILD_DEPENDENCIES||'').split(path.delimiter).filter(Boolean),esbuild=require(require.resolve('esbuild',{paths:[process.cwd(),...extra]}));
const threePath=require.resolve('three',{paths:[process.cwd(),...extra]}).replace('three.cjs','three.module.js'),checks=[];
class Target{constructor(tag='div'){this.tagName=tag.toUpperCase();this.events=new Map();this.children=[];this.style={};this.attributes={};this.dataset={};this.hidden=false;this.checked=false;this.disabled=false;this.clientWidth=393;this.clientHeight=760;this.captured=new Set();this.classList={values:new Set(),add(...ns){ns.forEach(n=>this.values.add(n));},remove(...ns){ns.forEach(n=>this.values.delete(n));},toggle(n,on){if(on)this.add(n);else this.remove(n);}};}addEventListener(n,f){if(!this.events.has(n))this.events.set(n,[]);this.events.get(n).push(f);}removeEventListener(n,f){this.events.set(n,(this.events.get(n)||[]).filter(v=>v!==f));}setAttribute(n,v){this.attributes[n]=v;}append(...xs){this.children.push(...xs);}replaceChildren(){this.children=[];}querySelector(s){return document.querySelector(s);}getRootNode(){return document;}getBoundingClientRect(){return {left:0,top:0,width:this.clientWidth,height:this.clientHeight};}setPointerCapture(n){this.captured.add(n);}hasPointerCapture(n){return this.captured.has(n);}releasePointerCapture(n){this.captured.delete(n);}count(){return [...this.events.values()].reduce((a,b)=>a+b.length,0);}}
const html=fs.readFileSync('dist/index.html','utf8'),elements=new Map(),viewButtons=[],modeButtons=[],moveButtons=[];
const markup=html.replace(/<script[\s\S]*?<\/script>/g,'').replace(/<style[\s\S]*?<\/style>/g,'');
for(const match of markup.matchAll(/<([\w-]+)\b([^>]*?)>/g)){const element=new Target(match[1]),attrs=match[2];for(const a of attrs.matchAll(/([\w-]+)="([^"]*)"/g)){element.attributes[a[1]]=a[2];if(a[1]==='id')elements.set('#'+a[2],element);if(a[1].startsWith('data-'))element.dataset[a[1].slice(5)]=a[2];}element.hidden=/\bhidden\b/.test(attrs);element.checked=/\bchecked\b/.test(attrs);if(element.dataset.view)viewButtons.push(element);if(element.dataset.mode)modeButtons.push(element);if(element.dataset.move)moveButtons.push(element);}
const document=new Target('document');document.readyState='complete';document.hidden=false;document.documentElement=new Target('html');document.querySelector=s=>elements.get(s);document.querySelectorAll=s=>s==='[data-view]'?viewButtons:s==='[data-mode]'?modeButtons:s==='[data-move]'?moveButtons:[];document.createTextNode=t=>({textContent:t});document.createElement=t=>{const e=new Target(t);e.ownerDocument=document;return e;};for(const e of elements.values())e.ownerDocument=document;
elements.set('#room-seed',new Target('script'));elements.get('#room-seed').textContent=html.match(/<script id="room-seed" type="application\/json">([\s\S]*?)<\/script>/)[1];
const window=new Target('window');document.defaultView=window;window.roomBoot={progress(){},ready(){this.loaded=true;},fail(message){throw Error(message);},setPanel(){}};let next=1,raf=new Map();global.document=document;global.window=window;global.navigator={userAgent:'iPhone test double'};global.matchMedia=()=>({matches:true});global.devicePixelRatio=3;global.ResizeObserver=class{observe(){}};global.requestAnimationFrame=fn=>{const id=next++;raf.set(id,fn);return id;};global.cancelAnimationFrame=id=>raf.delete(id);
const out=path.resolve('.sites-runtime/viewer_integration.cjs');fs.mkdirSync(path.dirname(out),{recursive:true});
class StubRenderer{constructor(){global.lastRenderer=this;}setPixelRatio(){}setSize(){}render(scene,camera){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);this.scene=scene;this.camera=camera;this.renders=(this.renders||0)+1;}}
global.__RoomStubRenderer=StubRenderer;
(async()=>{await esbuild.build({entryPoints:['dist/viewer.js'],outfile:out,bundle:true,platform:'node',format:'cjs',nodePaths:extra.map(p=>path.join(p,'node_modules')),plugins:[{name:'math-only-renderer',setup(build){build.onResolve({filter:/^three$/},()=>({path:'three-for-math',namespace:'qa-three'}));build.onLoad({filter:/.*/,namespace:'qa-three'},()=>({contents:'export * from '+JSON.stringify(threePath)+'; export const WebGLRenderer=globalThis.__RoomStubRenderer;',loader:'js',resolveDir:process.cwd()}));}}]});require(out);await new Promise(resolve=>setTimeout(resolve,20));assert(window.roomBoot.loaded);const api=window.roomViewer,canvas=elements.get('#canvas'),baseline=canvas.count();const batches=api.getState().drawBatches;assert(batches>=29&&batches<60,'draw batches '+batches);
 for(const mode of ['floorplan','decoration','immersive']){api.setMode(mode);api.setView(mode==='floorplan'?'top':mode==='immersive'?'bedfoot':'bedroom');const before=api.getState(),camera=global.lastRenderer.camera,position=[...before.camera],layers={...before.layers};api.setRoam(true);for(let i=0;i<4;i++){const callbacks=[...raf.values()];raf.clear();callbacks.forEach(fn=>fn(1000+i*17));}const active=api.getState();assert(active.roam.active&&active.roam.firstPerson);assert.equal(global.lastRenderer.camera.fov,70);assert(elements.get('#labels').hidden);assert.equal(['touchstart','touchmove','touchend','touchcancel'].reduce((n,k)=>n+(canvas.events.get(k)||[]).length,0),0);assert.equal(elements.get('#roam-hud').hidden,false);api.setRoam(false);const after=api.getState();assert.equal(after.mode,before.mode);assert.equal(after.view,before.view);assert.deepEqual(after.layers,layers);for(let i=0;i<3;i++)assert(Math.abs(after.camera[i]-position[i])<.00001);assert.equal(canvas.count(),baseline);assert.equal(elements.get('#roam-hud').hidden,true);assert.equal(elements.get('#labels').hidden,mode!=='floorplan');assert.equal(global.lastRenderer.camera.fov??42,42);checks.push(mode+' → first-person → original camera/layers/touch handlers restored');}
 for(let i=0;i<20;i++){api.setRoam(true);api.setRoam(false);}assert.equal(canvas.count(),baseline);checks.push('twenty full Viewer enter/exit cycles retain original touch handlers');
 const result={version:'1.3.0',passed:true,checks,verification:'Actual viewer.js executed in Node with real Three.js/OrbitControls, DOM event doubles and a stub renderer; no browser or GPU execution'};fs.writeFileSync('dist/viewer_integration_checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));})().catch(e=>{console.error(e);process.exitCode=1});
